// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa80RvYZ3BE3637j29m6FKy9_Hl15e4uQ',
    appId: '1:485861325401:android:65606d613554a6bae94f48',
    messagingSenderId: '485861325401',
    projectId: 'lsaig-5o4m2',
    storageBucket: 'lsaig-5o4m2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1dx1OgU43G0uwiNXtWmMNzci-bfN58EI',
    appId: '1:485861325401:ios:1eaf71eeda1f0cd0e94f48',
    messagingSenderId: '485861325401',
    projectId: 'lsaig-5o4m2',
    storageBucket: 'lsaig-5o4m2.firebasestorage.app',
    androidClientId: '485861325401-2t3ilpt7hsgqpkj04nrjcdd4abfn741o.apps.googleusercontent.com',
    iosClientId: '485861325401-frpmt9m84erqi1h46qol49408n6hoohc.apps.googleusercontent.com',
    iosBundleId: 'com.selene.seleneChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVqQ2lAbTHfxnOs1VT1yJQKRAkWJDf48',
    appId: '1:485861325401:web:ba7f3db32d8e19ffe94f48',
    messagingSenderId: '485861325401',
    projectId: 'lsaig-5o4m2',
    authDomain: 'lsaig-5o4m2.firebaseapp.com',
    storageBucket: 'lsaig-5o4m2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1dx1OgU43G0uwiNXtWmMNzci-bfN58EI',
    appId: '1:485861325401:ios:1eaf71eeda1f0cd0e94f48',
    messagingSenderId: '485861325401',
    projectId: 'lsaig-5o4m2',
    storageBucket: 'lsaig-5o4m2.firebasestorage.app',
    androidClientId: '485861325401-2t3ilpt7hsgqpkj04nrjcdd4abfn741o.apps.googleusercontent.com',
    iosClientId: '485861325401-frpmt9m84erqi1h46qol49408n6hoohc.apps.googleusercontent.com',
    iosBundleId: 'com.selene.seleneChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFVqQ2lAbTHfxnOs1VT1yJQKRAkWJDf48',
    appId: '1:485861325401:web:ba7f3db32d8e19ffe94f48',
    messagingSenderId: '485861325401',
    projectId: 'lsaig-5o4m2',
    authDomain: 'lsaig-5o4m2.firebaseapp.com',
    storageBucket: 'lsaig-5o4m2.firebasestorage.app',
  );

}